version: '3.7'

services:
  walleserver:
    build:
      context: .
      dockerfile: dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: walleserver
    expose:
      - '8080'
    ports:
      - '8080:8080'
    command: npm run dev
